import type { SeoPage } from "@/lib/seo";

export type EnglishProjectCopy = Pick<SeoPage, "title" | "description" | "h1" | "imageAlt"> & {
  category: string; liveTitle: string; firstLabel: string; firstTitle: string; firstBody: string;
  secondLabel: string; secondTitle: string; secondBody: string; relatedLabel: string; commercialQuestion: string; commercialCta: string;
};

export const englishProjects = {
  terrambu: { title: "Terrambu | Corsteno", description: "A responsive web experience for a boutique hotel in Córdoba, Argentina, built around its identity, visual content and the information needed to move toward a booking or inquiry.", h1: "Terrambu", imageAlt: "Terrambu hotel web experience developed by Corsteno", category: "CLIENT PROJECT · WEB DEVELOPMENT", liveTitle: "Explore the project", firstLabel: "The challenge", firstTitle: "Discover the hotel before visiting.", firstBody: "Present rooms, dining and surroundings through a clear visual experience without losing the hotel's own identity.", secondLabel: "The solution", secondTitle: "The character of the place, brought to the browser.", secondBody: "We designed and developed a responsive experience focused on visual content, room exploration and clear access to hotel information.", relatedLabel: "See web development", commercialQuestion: "Want to build something like this for your business?", commercialCta: "Let's discuss your project" },
  "mapa-punilla": { title: "Mapa Punilla | Corsteno", description: "A map-based platform for Punilla, a major tourist region of Córdoba, Argentina, turning territorial information into a visual, explorable experience.", h1: "Mapa Punilla", imageAlt: "Mapa Punilla interactive platform developed by Corsteno", category: "CLIENT PROJECT · INTERACTIVE PLATFORM", liveTitle: "Explore the project", firstLabel: "The challenge", firstTitle: "Organize a territory so it can be explored.", firstBody: "Bring together places and points of interest across the Punilla Valley in a visual experience that makes discovery easier.", secondLabel: "The solution", secondTitle: "The territory as a digital product.", secondBody: "We developed an interactive map-based platform with data structure and a responsive interface for exploring territorial information.", relatedLabel: "See web development", commercialQuestion: "Want to build something like this for your business?", commercialCta: "Let's discuss your project" },
  "revestimientos-interactivos": { title: "Interactive Finishes | Corsteno", description: "Explore combinations of floors, walls and finishes in real time inside a 3D environment.", h1: "Interactive Finishes", imageAlt: "Interactive 3D finishes experience developed by Corsteno", category: "CORSTENO LAB · INTERIOR FINISHES 3D", liveTitle: "Explore the finishes", firstLabel: "The concept", firstTitle: "Compare before choosing.", firstBody: "The experience lets people try floors, walls, bar finishes and openings directly within an interior environment.", secondLabel: "What it demonstrates", secondTitle: "Finishes in context.", secondBody: "The demo combines model-based variants, 3D navigation, touch controls, reset and fullscreen without turning furniture into a configurable option.", relatedLabel: "See 3D visualization", commercialQuestion: "Want to build something like this for your business?", commercialCta: "Let's discuss your project" },
  "exterior-house": { title: "Exterior House | Corsteno", description: "A conceptual experience for exploring pool materials and finishes directly in the browser.", h1: "Exterior House", imageAlt: "Exterior House interactive 3D experience developed by Corsteno", category: "CORSTENO LAB · ARCHITECTURAL 3D", liveTitle: "Try the configurator", firstLabel: "The concept", firstTitle: "Choose materials before building.", firstBody: "Exterior House lets people compare water, waterfall, coping, interior and outdoor flooring on an interactive pool.", secondLabel: "What it demonstrates", secondTitle: "Outdoor finishes in context.", secondBody: "The demo combines model-based variants, coping color changes, 3D navigation, reset and fullscreen.", relatedLabel: "See 3D visualization", commercialQuestion: "Want to build something like this for your business?", commercialCta: "Let's discuss your project" },
} as const satisfies Record<string, EnglishProjectCopy>;
