import { localizedRoutes } from "@/lib/i18n/routes";
export type CapabilityCase = { id: string; title: string; status: "published" | "in-development" | "planned"; href?: string };
export type CapabilityVertical = { id: string; title: string; slug: string; priority: "primary" | "secondary"; description: string; cases: CapabilityCase[]; relatedCapabilities: string[] };
export const capabilityVerticals: CapabilityVertical[] = [
  { id: "brand_activation", title: "Activaciones de marca", slug: "activaciones-de-marca", priority: "primary", description: "Tecnología interactiva para campañas, eventos y experiencias gamificadas.", cases: [{ id: "beverages-activation", title: "Activación interactiva — Bebidas", status: "in-development" }, { id: "food-gamified-experience", title: "Experiencia gamificada — Alimentos", status: "in-development" }], relatedCapabilities: ["ar_xr", "interactive_3d"] },
  { id: "ar_xr", title: "AR / XR", slug: "realidad-aumentada", priority: "primary", description: "Experiencias que llevan contenido digital al espacio físico.", cases: [{ id: "cosquin-rock-ar", title: "Cosquín Rock AR", status: "in-development" }, { id: "ar-experience-02", title: "Otra experiencia AR", status: "planned" }], relatedCapabilities: ["brand_activation", "interactive_3d"] },
  { id: "interactive_3d", title: "3D interactivo", slug: "configuradores-3d", priority: "secondary", description: "Productos y espacios explorables, configurables y comprensibles en tiempo real.", cases: [{ id: "interactive-finishes", title: "Revestimientos Interactivos", status: "published", href: localizedRoutes.projects["revestimientos-interactivos"].es }, { id: "exterior-house", title: "Revestimientos de exterior", status: "published", href: localizedRoutes.projects["exterior-house"].es }], relatedCapabilities: ["ar_xr", "web_experiences"] },
  { id: "web_experiences", title: "Experiencias Web", slug: "desarrollo-web", priority: "secondary", description: "Plataformas y sitios construidos alrededor de una experiencia.", cases: [{ id: "terrambu", title: "Terrambú", status: "published", href: localizedRoutes.projects.terrambu.es }, { id: "mapa-punilla", title: "Mapa Punilla", status: "published", href: localizedRoutes.projects["mapa-punilla"].es }], relatedCapabilities: ["interactive_3d", "brand_activation"] },
];
